server:
  port: 8084
  servlet:
    context-path: /novel
spring:
  application:
    name: novel-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/novel-service?authSource=admin
imgur:
  client-id: 5797e36b930c74e
  client-secret: df8d93bbe36be2d30905605215152b92b7e96c97