server:
  port: 8888
app:
  api-prefix: /api
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1
        - id: novel-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/novel/**
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/comment/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/search/**
          filters:
            - StripPrefix=1