server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/profile-service?authSource=admin
imgur:
  client-id: 5797e36b930c74e
  client-secret: df8d93bbe36be2d30905605215152b92b7e96c97
app:
  services:
    novel: http://localhost:8084/novel
