server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/search-service?authSource=admin
